export { IconArrowRight } from './mono/IconArrowRight'
export { IconCheck } from './mono/IconCheck'
export { IconCopy } from './mono/IconCopy'
export { IconPocMark } from './color/IconPocMark'
export type { IconSvgProps } from './types'
